### ISSUE TITLE
Flags (specifically, problems relating to them)

### ISSUE THREAD

**Issue by Jtecx** [Chase-san/TiTsEd#101]
Dick Nipple types are incomplete, missing newer types beyond human, equine, feline and canine.

~~Also, is item flag editing going to be a thing? I see it being mentioned ever since the start, and I've delved into the save itself on minerva, but I don't seem to be able to change the flags on items. Or is this a set value built in-game instead, and not possible on the save side?~~  ~~Wait just saw this was resolved as a non-fixable.~~ Potential solution found. It seems that the items are "standard", but only if they do not have the boolean "hasRandomProperties". Could it be possible to retroactively add the boolean to the item? Currently testing if the flags remain after storage, restart of game with restored save state, and other ideas.

Last, might I suggest a reorganization of the flags for body parts? Perhaps group them by changeable attributes, like the nubby/ribbed phallus type, amorpheous/digitgrade/tendril legs, etc.

**Comment by algoRhythm99** [comment]
"Could it be possible to retroactively add the boolean to the item? " 
No. 
Only the items that have that flag in the source code will work the way you are expecting. 

As for organization, what are you talking about?

**Comment by Jtecx** [comment]
"Only the items that have that flag in the source code will work the way you are expecting"
Hm, alright. Perhaps the effects don't get triggered, but the stats do show up on player equipment. Interesting effect though. Not pushing any further on this.

For organization, I would kindly ask you to look at the way the flags for the legs, penis and vagina are sorted, or rather, the lack thereof, unless there is a pattern, but I am missing it? Specifically, for example, perhaps either group "Nubby" and "Ribbed" in one subcategory, since they don't actually seem to both get stated on the appearance tab. Just a suggestion.

**Comment by algoRhythm99** [comment]
Whether any particular flag shows up or not in a description is completely at the mercy of the game engine and could technically change at any time.
The editor just lets you add the flags to the part from the list.
So trying to maintain a list of categories like that wouldn't make sense.
