### ISSUE TITLE
No Executable File

### ISSUE THREAD

**Issue by Vitalis597** [Chase-san/TiTsEd#104]
Downloaded the Zip file from "https://github.com/Chase-san/TiTsEd", unzipped, looked in each and every folder, tried running literally everything that looked remotely like it could be an exe file, nothing ran.

A few things tried opening Microsoft Edge, but that either lead to it telling me to reload the page, or giving me a bunch of text about the different species. Nothing resembling a save editor.

**Comment by algoRhythm99** [comment]
Binaries are linked on the release versions page:
https://github.com/Chase-san/TiTsEd/releases
The binary zips are named TiTsEd_v####.zip
ie, https://github.com/Chase-san/TiTsEd/releases/download/v0.30.6/TiTsEd_v0.30.6.zip
