### ISSUE TITLE
Status Effect Request

### ISSUE THREAD

**Issue by TheoreticalGoodra** [Chase-san/TiTsEd#105]
There's an obscure status effect called "Opaque Skin" which is unavailable through normal play that I would like to be able to edit onto characters. I used to use Minerva to do it so it should be possible and since Minerva's in a pretty feature incomplete state right now I thought I'd just make a request here. Plus who knows, maybe someone else would also appreciate it for their goo characters.

**Comment by algoRhythm99** [comment]
Will be in the next release
