### ISSUE TITLE
Higher Values?

### ISSUE THREAD

**Issue by Hiro-LordOfAThousandSongs** [Chase-san/TiTsEd#106]
I'm curious if it's at all possible to increase the maximum value (For most we can change) from "**268435455**" to something higher.
-------------------------------------------------------------------------------------------------------
![Desktop Capture-03-05-2020 16-21-50-872](https://user-images.githubusercontent.com/61854015/76038150-bb47c080-5efd-11ea-89e2-942490f78444.jpg)
![Desktop Capture-03-05-2020 16-21-50-872 (2)](https://user-images.githubusercontent.com/61854015/76038149-baaf2a00-5efd-11ea-92ef-f38f541c49fc.jpg)
-------------------------------------------------------------------------------------------------------
The credits value is something i managed by using CE (Cheat Engine) and is **1Qa**.

Energy (maximum) and stat values are **268.4Mil**, except for Willpower which is **322.1Mil** in-game.
HP Is **805.3Mil**, Shields is **536.9Mil**.

HP and Shields values were only possible after saving at a value lesser than **268435455**, and going in-game, sleeping then saving and loading with TiTSED.

All i really want is to be able to make values higher than **268.4Mil**, without taking extra, unnecessary steps.

**Comment by Chase-san** [comment]
Is it possible. Certainly.

Is there a reason to do so. Absolutely not. In actuality some of the current limits should be drastically decreased if they can actually go that high.

Nothing in the game requires (or even allows) any of these values to be such large amounts, in fact setting it that high might undefined behavior in the game, which we try to avoid where possible.

**Comment by Hiro-Mastermind** [comment]
I've not noticed any issues with getting values that high so far, and the last Public patch abbreviates values, regardless of whether they should actually be capable of getting high enough to BE abbreviated.

**Comment by algoRhythm99** [comment]
What's the use-case for setting them so high?
Just wanting bigger numbers?

**Comment by Hiro-Mastermind** [comment]
Mostly. But the addition of numbers being abbreviated now, is why i ask, since before it'd glitch into the text, now it won't and people can read values that high without issues. It's also fun to see just how high values can get with the abbreviation system in place.

Although i would like to ask for two more things, since you (Highly likely) won't do the one i want most.

Allowing numbers to be typed as "1-9e1-999" just so we don't have to type out the big numbers that can be used in some areas. And allowing negative values to be typed in, since we currently can't. (Don't remember why exactly i wanted this though)

**Comment by algoRhythm99** [comment]
Can you attach a save file?
I'm curious how ActionScript actually stores those values.

**Comment by Hiro-Mastermind** [comment]
Lemme try, i haven't updated TiTS in a while, and haven't ever tried to save files.

(After this I'm not gonna update until the end of the month, because updating every couple days is gonna get tedious)

**Comment by Hiro-Mastermind** [comment]
Can't attach a save file, GitHub doesn't support it. (Likely because the file type is unique)

I can change the file type (.[Type]) but I don't know what the effects would be on the save file.

**Comment by algoRhythm99** [comment]
Upload it to like Dropbox or another file storage and link 👍

**Comment by Hiro-Mastermind** [comment]
I've never used Storage File stuff...

Will putting it in a file then compressing work, without (potentially) damaging the file?

**Comment by algoRhythm99** [comment]
Yes, zipping wont break it, and changing the extension doesn't affect the file either, though it might not trick GitHub

**Comment by Hiro-Mastermind** [comment]
[TiTS Save File.zip](https://github.com/algoRhythm99/TiTsEd/files/4433013/TiTS.Save.File.zip)

I think it worked?

**Comment by Hiro-Mastermind** [comment]
OH YEAH. So, I totally just remembered something else, that likely shouldn't be here.

It's the "Tachyon Beam Laser" item, Weapons section. If it's put into a save, it breaks that save (You can't use it in-game at all) until you remove it, after which the save works just fine.
