### ISSUE TITLE
Won't function

### ISSUE THREAD

**Issue by MERGINGAPPLES** [Chase-san/TiTsEd#107]
Program will load and open, but upon clicking "open" or any other button in the program it just closes. No error code and windows event logger isn't giving me anything productive to go off of. All buttons up top are blacked out (not that they can be clicked on anyway). Any ideas how to fix this?

**Comment by algoRhythm99** [comment]
Try this version
https://github.com/algoRhythm99/TiTsEd/releases/download/v0.30.8/TiTsEd_v0.30.8.zip 

There should be a log file in %LOCALAPPDATA%\TiTsEd, attach that

**Comment by MERGINGAPPLES** [comment]
[TiTsEd.log](https://github.com/algoRhythm99/TiTsEd/files/4333394/TiTsEd.log)
That version is also not functioning, here is the log as requested.

**Comment by algoRhythm99** [comment]
I see this in the log:
"C:\Users\mergi\AppData\Local\Temp\Rar$EXa18508.39660\TiTsEd.exe"

This looks like you didn't actually extract the files?

**Comment by MERGINGAPPLES** [comment]
Extracted or no I can't make it work You are correct in this last run it wasn't extracted into any folder, here is a new log from the version you sent me that I tried running after extracting it to a folder. Still no luck.
[TiTsEd.log](https://github.com/algoRhythm99/TiTsEd/files/4333561/TiTsEd.log)

**Comment by algoRhythm99** [comment]
https://github.com/algoRhythm99/TiTsEd/releases/download/v0.30.8/TiTsEd_v0.30.8.zip 
Can you try this updated version and attach the log?
Added some additional logging

**Comment by MERGINGAPPLES** [comment]
Well, something different happened. It took a good 30 seconds to crash out instead of the normal 2-3.
Here is the new log as requested.
(All files were extracted and attempted to run as admin)
[TiTsEd.log](https://github.com/algoRhythm99/TiTsEd/files/4338646/TiTsEd.log)

**Comment by algoRhythm99** [comment]
https://github.com/algoRhythm99/TiTsEd/releases/download/v0.30.8/TiTsEd_v0.30.8.zip

Added additional logging,
also, it should create a crash dump file at 
%LOCALAPPDATA%\CrashDumps

Can you link or attach it, might not let you attach, will be ~ 30 mb

**Comment by Fortilicious** [comment]
I am also having this issue.  The file path for Windows 7 is C:\Users\Owner\AppData\Local\CrashDumps.  
The file type generated is a .dmp and is not compatible with this website.
I've uploaded the file you asked MERGINGAPPLES to upload to my google drive here:
https://drive.google.com/open?id=1nR8aQ7u3hu63rFg68NZtCEYVqKLF3mkp

**Comment by algoRhythm99** [comment]
Seems to be crashing inside of the .NET runtime itself.

https://github.com/algoRhythm99/TiTsEd/releases/download/v0.30.8/TiTsEd_v0.30.8.zip

Even more logging, can you attach the log file so I can try to narrow it down further?

**Comment by Fortilicious** [comment]
seems like it is no longer having this issue.  I was able to open with no issues.

**Comment by algoRhythm99** [comment]
@MERGINGAPPLES does this https://github.com/algoRhythm99/TiTsEd/releases/download/v0.30.8/TiTsEd_v0.30.8.zip version fix it for you as well?
If not attach the log and link the crash dump file

**Comment by MERGINGAPPLES** [comment]
still breaking for me. still evading my efforts to fix it. new log file.
[TiTsEd.log](https://github.com/algoRhythm99/TiTsEd/files/4384347/TiTsEd.log)
sorry to reply so late.

**Comment by algoRhythm99** [comment]
"OpenButton_Click: End"

This means that the open button handler has finished, and the crash is happening entirely in the .NET runtime.

Note sure if there is anything I can do to stop this.

**Comment by MERGINGAPPLES** [comment]
Odd, I uninstalled all microsoft net framework and suddenly it works. because, reasons, I guess.

this is why I bailed on being in IT.

**Comment by algoRhythm99** [comment]
Gonna mark this as fixed for now then.
