### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by GoreStrider** [Chase-san/TiTsEd#111]
I was using it fine until last night. It gave me a strange error box and I have no clue how to fix it. The error is:  
![Untitled](https://user-images.githubusercontent.com/66791508/84406706-879cc680-abcf-11ea-9883-cbc3fd234e41.png)

**Comment by algoRhythm99** [comment]
Make sure the app is closed and then delete %LOCALAPPDATA%\TiTsEd folder
