### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by Damienteran19** [Chase-san/TiTsEd#112]
I've downloaded the file, extracted the file, then I've tried to run application, and everytime I've tried, the application wont launch. Instead, a little popup asks me if I want information on why it won't launch (twice every time I might add) but doesn't tell me what's wrong. Please help, I have no idea what to do.

**Comment by Damienteran19** [comment]
Nevermind, I figured out what I was doing wrong. I needed to redownload the zip file and save it rather than immediately open.

**Comment by Damienteran19** [comment]
Quick question though, in the ship creation mode, there is no way to tell where your newly made ships are. Is there a set location, or do I have to manipulate another ship that I have already bought?

**Comment by algoRhythm99** [comment]
Adding ships isn't really supported at this time.
Editing the ships should be treated with caution.
