### ISSUE TITLE
TiTsEd can't overwrite save

### ISSUE THREAD

**Issue by Thenfulk** [Chase-san/TiTsEd#113]
![Screenshot_5](https://user-images.githubusercontent.com/59069263/86514317-f4dbfa00-be11-11ea-81ae-b1ca5eb30338.jpg)
This appear when i try to save edited game as file

**Comment by algoRhythm99** [comment]
That means the permissions on the file are such that it can't overwrite it, either due to it being in use or the account TiTsEd is running as not having write permissions.

Not a bug in TiTsEd
