### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waltherwhite36** [Chase-san/TiTsEd#114]
[C:\Users\walth\Downloads\TiTsEd.exe:0.30.8.37283:Microsoft Windows NT 6.2.9200.0:Unknown]
System.Configuration.ConfigurationErrorsException: Elemento raiz inexistente. (C:\Users\walth\AppData\Local\TiTsEd\TiTsEd.exe_Url_r4jd5kpbkz1cg3d1hjejdh453gs05njs\0.30.8.37283\user.config) ---> System.Xml.XmlException: Elemento raiz inexistente.
   em System.Xml.XmlTextReaderImpl.Throw(Exception e)
   em System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   em System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   em System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   em System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   em System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   em System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   em System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   em System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   em System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   em System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   em System.Configuration.ApplicationSettingsBase.Upgrade()
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by algoRhythm99** [comment]
Make sure TiTsEd is closed (all windows), and delete C:\Users\walth\AppData\Local\TiTsEd
