### ISSUE TITLE
Transfering Save Data to New Game

### ISSUE THREAD

**Issue by Damienteran19** [Chase-san/TiTsEd#121]
I recently updated my internet explorer app as well as your own update of the TiTS Ed, and I'm not sure which did it, but all of my save data on the Online Version of TiTS got deleted. Rather than try to search for it (before realizing I had a few downloaded files on my hard drive), I just decided to start a new game. Problem is, the Editor is still hooked up to my old saves. Is there a way to link it to the new online saves, or am I stuck with downloading save files onto my hardrive, then redownloading said files once edited and then reuploading them to the online game?

**Comment by algoRhythm99** [comment]
What do you mean by "internet explorer app"? Your browser?
The editor knows about where many browsers store the flash files, but maybe not that one.
What browser are you using?

**Comment by Damienteran19** [comment]
Microsoft Edge. Something about internet explorer getting shut down and replaced with Microsoft Edge refreshed the Fenoxo link to the online verstion of TiTS and now the data is up in the wind. I can't really think of a way to open the TiTS editor and change it's online saves to the new game without returning to my old save files on internet explorer.

**Comment by algoRhythm99** [comment]
Internet Explorer online saves show up as "Online (Standard)"

Older Edge would show up in the list as "Online (Edge/Metro)"

I just added support for the Chromium-based version of Edge, which will show up in the list as "Online (Edge)".
