### ISSUE TITLE
Trojan Horse?

### ISSUE THREAD

**Issue by TheFlumph** [Chase-san/TiTsEd#122]
My AntiVirus is detecting a Trojan Horse in the files for this program. I figured I would post a warning. This could be a case of my Antivirus not detecting the files correctly but I don't have the skills to detect if this is true or not.

**Comment by xoiifluffy** [comment]
Came to see if the update was bugged or not due to this same issue.

**Comment by algoRhythm99** [comment]
Its a false positive:
https://www.virustotal.com/gui/url/a48fa018218dff0492f48384de64a633db7d1fc168ac756a30ac94421152b45b/details
