### ISSUE TITLE
mottling option missing on Genitals

### ISSUE THREAD

**Issue by Fortilicious** [Chase-san/TiTsEd#125]
Currently, the only mottling option in TiTsEd for cocks is "Mottled brown".  When using the "Synthsheath" item, the transformative gives you a equine penis with a coloration "Mottled black and pink".  This coloration option is not readily available in TiTsEd.  TiTsEd only shows it after using the item and if you change it, the option is gone.

**Comment by algoRhythm99** [comment]
Fixed in next release.
FYI, you can actually type anything you want into the color boxes
