### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by ghost** [Chase-san/TiTsEd#126]
I am seeing success using TiTsEd with wine-6.0rc2 from TKG.
WINEARCH is win32, and dotnet40 is installed on the prefix.

Only noticeable issues are poor font quality, but it doesn't affect usability much.

If a few people can replicate, it may be time to update the readme to reflect the change in support from WINE.

**Comment by mario-marin** [comment]
Im using lutris with the latest TKG build (6.0.r0.g2414b1da), also WINEARCH win32 and I installed dotnet40, additionally I disabled DXVK (enabled by default in lutris).

As mentioned the font is not perfect but perfectly usable, I have found no issues on loading or saving edited saves, the game recognised all the changes correctly.

I will inform if I find anything wrong.

**Comment by Chase-san** [comment]
It working on Linux and wanting to support users using Linux are entirely different things.

We can remove the line saying that it does not work, but clarify that it is not designed for or tested on any non-windows platform.

**Comment by mario-marin** [comment]
Sounds good to me :3

**Comment by algoRhythm99** [comment]
Updated the requirements to state .NET 4.5 or later and only tested on Windows.
