### ISSUE TITLE
Preset

### ISSUE THREAD

**Issue by Drakirumbra** [Chase-san/TiTsEd#127]
Hello. I was wondering If you could add a list for us to save preset of appearence (general, head, body and genitals) ?
I was also wondering if there is a way to make it in game (If I remember you can't since it would mean adding an item to the game, thing that you can't do right?)

Sorry I wrote this at he wrong place.

**Comment by algoRhythm99** [comment]
Can't add things to the game, can only edit saves.

Likely won't be doing this request, but I'll take pull requests if anyone wants to implement it.

**Comment by Drakirumbra** [comment]
It's as I tought for the second part. Anyway thanks for answering me.
