### ISSUE TITLE
inventory slots in app

### ISSUE THREAD

**Issue by akenken** [Chase-san/TiTsEd#128]
the inventory slots are at 20 in game and when i first load the save in the editor it says 20, until i click on a slot past 10 then drops to ten even
edit: only drops to ten after i try putting an item in the slot
can change the quantity in the second half but cant add a new thing into my inventory without it wigging out like it is
when it does this it deletes my inventory past ten slots
happens on a brand new clean save even
 i dont know if youll keep this but a pc restart and nothings wrong

**Comment by algoRhythm99** [comment]
Max Inventory items is based on a few things, such as if you have the 'Backpack Upgrade' status effect, the 'Hidden Loot' perk,  cargobot accessory, or "Insulated Coat" armor.
The default is 10, which it would be if you had none of those listed above.

**Comment by akenken** [comment]
i had gotten to the 20 slot bag and bought it and used it but it wasn't registering i had 20 slots for some reason, again i restarted the laptop and everything worked as intended so i don't know if you'll keep this around to see about a potential problem or not
