### ISSUE TITLE
Update Checker Error

### ISSUE THREAD

**Issue by someonenameguy** [Chase-san/TiTsEd#129]
The update checker gives an error "Check failed. An unexpected problem occurred.".
I have no idea what's causing it. I have internet and it used to work.

![image](https://user-images.githubusercontent.com/54163580/107359751-09067900-6b10-11eb-9da4-e1871ef59162.png)

**Comment by algoRhythm99** [comment]
The .NET Runtime seems to be having issues with Github's cert:
"The request was aborted: Could not create SSL/TLS secure channel"

**Comment by algoRhythm99** [comment]
Will be fixed in the next release.
Accessing raw.githubusercontent.com (as it does to get the latest.txt file) requires using TLS 1.2 or later, and the .NET runtime defaults to 1.0.
This next release will no longer support Windows XP at all, as it will now require .NET 4.5.
