### ISSUE TITLE
Alcohol Tolerance value doesn't change in game.

### ISSUE THREAD

**Issue by Rowdyhorse4** [Chase-san/TiTsEd#131]
Alcohol Tolerance value doesn't change in game after a save edit. (example case)
![Capture](https://user-images.githubusercontent.com/29912767/111996059-37826580-8b4c-11eb-8939-e3b827781636.PNG)

**Comment by algoRhythm99** [comment]
Cannot duplicate this.
Are you editing the alcohol tolerance for other characters?

**Comment by Rowdyhorse4** [comment]
My own character, Different saves or new characters, still no effect, Alcohol tolerance level doesn't change.

**Comment by algoRhythm99** [comment]
Can you attach a save that is showing this problem?
And the %LOCALAPPDATA%\TiTsEd\TiTsEd.log file?

**Comment by Rowdyhorse4** [comment]
[bug.zip](https://github.com/algoRhythm99/TiTsEd/files/6199060/bug.zip)

Here's the files you need. I should also say when i tested it again, this issue doesn't happen with a fresh new save. Only happens after playing for some time. I think it refuse to edit if you started the game and already organically gained some alcohol tolerance? Similar bug may have occurred as well to exhibitionism.

**Comment by Rowdyhorse4** [comment]
Also be aware this is using the Image Pack 0.8.134

**Comment by algoRhythm99** [comment]
Found the bugs, its actually much worse than just the alcohol tolerance problem.
Its a general issue with the perks/statuses/keyitems when loading more than one save.

**Comment by Rowdyhorse4** [comment]
Damn...   Did you know of this bug before this?

**Comment by algoRhythm99** [comment]
Nope, I'm usually running from the debugger and so just constantly restarting it..

**Comment by Rowdyhorse4** [comment]
huh, well glad i could help! good luck fixing it m8!

**Comment by Fig8Man** [comment]
> Found the bugs, its actually much worse than just the alcohol tolerance problem.
> Its a general issue with the perks/statuses/keyitems when loading more than one save.

Could this be why I'm not able to add new flags or even edit flag names at all?
I coulda swore I used to be able to do that in the past
