### ISSUE TITLE
save editor randomly stopped working

### ISSUE THREAD

**Issue by akenken** [Chase-san/TiTsEd#133]
save editor giving error now after years of use on several different laptops and a couple on this one.  but running from the zip file works. 
![error](https://user-images.githubusercontent.com/12479647/120810595-3214a480-c519-11eb-8180-196685be27ca.png)
edit: running from zip has now failed me too

**Comment by algoRhythm99** [comment]
You cannot run from inside the zip.
As explained in the readme you *MUST* extract the files somewhere.

**Comment by akenken** [comment]
i did and the extracted files stopped working, then just as a random idea to help troubleshoot i ran from the zip, which worked once
