### ISSUE TITLE
[bad feature request] linux and macos builds?

### ISSUE THREAD

**Issue by akirapink** [Chase-san/TiTsEd#136]
microsoft has been handing out .NET for linux and macos users for a while now, and for at least one of these two you wouldn't even need to buy any new hardware to test the app on
TiTS players who do save editing and users of Unix-like operating systems (probably) don't have much overlap, but it'd be nice to have the option to have prebuilt builds, especially when having .NET run on wine is hell to get working and doesn't even fully function

**Comment by algoRhythm99** [comment]
TiTsEd uses WPF, which isn't supported on non-Windows systems.
