### ISSUE TITLE
Not sure how i use the save editor 

### ISSUE THREAD

**Issue by Chillgizzard** [Chase-san/TiTsEd#137]
I downloaded the file, extracted into a new folder and i couldn't find an exe file also i tried to open the xaml files but they experienced an error.
Sorry if i missed something

**Comment by algoRhythm99** [comment]
That means you downloaded the source instead of the binaries.
These are the latest binaries at the moment:
https://github.com/algoRhythm99/TiTsEd/releases/download/v0.34.5/TiTsEd_v0.34.5.zip
