### ISSUE TITLE
Having trouble using the Editor

### ISSUE THREAD

**Issue by TeddyBrosevlt** [Chase-san/TiTsEd#139]
I'm trying to use the save editor and I don't really know the issue, the game is saving the file as a .Json and when I try to open it in the editor I get this message
[C:\Users\Sam\Desktop\DnD stuff\TiTsEd.exe:0.34.6.0:Microsoft Windows NT 6.2.9200.0:Unknown]
System.NotImplementedException: Unknown endianness
   at TiTsEd.Model.AmfReader.ReadStandardFile(AmfFile file, String& name)
   at TiTsEd.Model.AmfFile..ctor(String path)

**Comment by algoRhythm99** [comment]
The editor does not support JSON save files currently
