### ISSUE TITLE
Error Message: TiTsEd Could Not Read This File Correctly

### ISSUE THREAD

**Issue by CardinalBirb** [Chase-san/TiTsEd#142]
Hi, new to GitHub and the game/editor. Got this message while trying to import my save to the editor. I don't know anything about code, but here it is. Hope I'm doing this right.

![image](https://user-images.githubusercontent.com/86525025/195961846-166740ad-6b94-4c5a-8ca7-62183f5e4766.png)

Sorry I have no idea what the red rectangle is.

![image](https://user-images.githubusercontent.com/86525025/195961933-f069509d-3356-4869-a66f-092855a0aa63.png)

Got the above image when I continued. As for continuing after that, the editor stayed blank.

**Comment by algoRhythm99** [comment]
The editor does not support the JSON saves from the latest versions

**Comment by CardinalBirb** [comment]
Is the editor being updated? Or any plans or something of the sort?

**Comment by algoRhythm99** [comment]
No

**Comment by CardinalBirb** [comment]
Ok cool. Do you know of any other ways to edit new saves? Like, something or some way that does what TiTsEd did for older versions.

**Comment by algoRhythm99** [comment]
The JSON format is text, you could edit it with any text editor if you understand the structures and the values.

There is a "state editor" (not the same as a save editor:
https://forum.fenoxo.com/threads/titsedjs-a-game-state-editor-for-javascript-version.32419/

**Comment by CardinalBirb** [comment]
cool cool, thanks for the help. I don't fully understand the structure and values but it helps knowing that I can do it. toodles.
