### ISSUE TITLE
Support: Load issues (cont)

### ISSUE THREAD

**Issue by KieroVance** [Chase-san/TiTsEd#15]
you CAN'T just load a slot from the game into the editor, it has no options for it...the only options are import and backup...

if you have a tutorial im missing let me know atleast...theres no instructions...

so if i'm missing something, well, i am..because those are the two options, and theres nothing else i can see that i can do...you weren't exactly clear before you just closed the issue im having...

no clear instructions on how to use the program...which....isn't exactly a good thing when i have no clue how to use it...

unless im missing them...

**Comment by Chase-san** [comment]
Just because I closed an issue, that doesn't mean I am not still helping. An open issue means there is an ongoing issue with the program, which in this case, there isn't. I am still trying to assist you in the other issue. I still get emails in closed issues.

Issues are not really for support, at least I don't think so.

**Comment by Chase-san** [comment]
Anyway, despite that, what browser/os are you using?

**Comment by KieroVance** [comment]
spark, its basically chrome, but used with baidu anti virus, protected, but not over, even can download torrents... why?

**Comment by KieroVance** [comment]
also, didnt think you could see comments coming in live, i feel like an idiot refreshing for 5 minutes XD

**Comment by KieroVance** [comment]
i can save the game, i can load the game...i just don't understand the editor and how to open the save files...

**Comment by Chase-san** [comment]
Can you try using chrome or firefox for playing the game. It's likely that Spark saves some place that TiTsEd doesn't check. If you know where it saves it's SOL files that's another story (you can use import then), but otherwise there isn't much I can do.

**Comment by KieroVance** [comment]
the thing is, WHERE would i even look for chrome? its pretty much the same thing, just different layout and some extra things, if you can tell me where it would even save to for chrome, i might have a chance of finding it... unless you mean the save file, which i chose...

but ill try...

**Comment by Chase-san** [comment]
You shouldn't need to look for chrome, it will automatically load them for chrome since the program knows where to find the saves for Chrome.  It doesn't know where they are for Spark.

Where it saves varies by operating system and browser... and version of the browser... and actually version of the operating system.

**Comment by KieroVance** [comment]
okay im playing it in firefox and i made a save...now what? i click open in the editor, still only import and backup as options, and import takes me to a window which is defaulted to looking in the desktop

**Comment by Chase-san** [comment]
What operating system are you on?

**Comment by KieroVance** [comment]
pc windows 7

**Comment by Chase-san** [comment]
For windows 7 using firefox, your saves `should` be stored at C:\Users\USERNAME\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\SHARED OBJ ID\localhost

USERNAME is the username you are currently logged onto.
SHARED OBJ ID is the shared object id for flash, but there should only be a single folder in #SharedObjects for that, so just check that one. It should be a bunch of random letters and numbers, like "Q466V56Y" or something.

**Comment by KieroVance** [comment]
well...thats...an annoying place to get to...sooo...i have to play this on firefox if i want to edit it?

**Comment by KieroVance** [comment]
let me try it XD

**Comment by Chase-san** [comment]
Just try making a save in firefox first, and see if the editor automatically finds it (you may need to reopen the editor).

**Comment by KieroVance** [comment]
it's found it..._whispers finally_ XD

thanks, and sorry for wasting your time if i did... mabye you should add things like instructions so you don't deal with people like me XD, and if it doesn't auto detect it for them, say where they could find it, atlesast for the systems they use...that way you won't need to deal with multiple mes basically...XD

well, thanks, and as usual:
- Have a great day / night :D! ! !
