### ISSUE TITLE
Tone and Race not updating properly ingame

### ISSUE THREAD

**Issue by EliteKiller693** [Chase-san/TiTsEd#19]
I uh, I don't really know how all of this works but I thought you might appreciate me letting you know about any issues I ran across. Tone on the general page does not update in game and simply reads as having an "average middle" regardless of which end of the spectrum I save in the editor. Additionally despite having every single body part as a Gryvain, my description no longer will list me as a full Gryvain and is now stuck at half Gryvain even if in game I down several of the Gryvain transformation items. Apologies if this isn't helpful. Please let me know if there is a way to be more helpful with bug reports in the future.

**Comment by algoRhythm99** [comment]
I can't duplicate this.
When I make changes to the attributes on my saves it shows up in game.

Can you attach a save file that has this issue?

**Comment by EliteKiller693** [comment]
As soon as I figure out how, yes.

**Comment by EliteKiller693** [comment]
Sorry it took me so long to get back, I can't seem to find a way to upload thesave file with the issue on it. Every time I try I get a "this file type is not supported" error.

**Comment by EliteKiller693** [comment]
I think I figured out how to upload the file for you to look at. I created a repository on my profile and uploaded the bugged save file to that repository for you, it is public so you should be able to look at it. Let me know if this doesn't work and need it sent using a different method.

**Comment by algoRhythm99** [comment]
I can't duplicate your issue.
With the thickness set to your initial value of 3 and tone of 12, the body section ends with "Your middle is nice and smooth."
When I set the thickness to 100 and leave tone at 12, the body section ends with "Your middle is pretty decent-sized. There’s no real hiding it."

**Comment by algoRhythm99** [comment]
For the racial identifier, your character's Gryvain score is not high enough to be counted as a pure Gryvain (you need >= 9)
http://wiki.smutosaur.us/Racial_score_(TiTS)#Gryvain
https://github.com/OXOIndustries/Trials-in-Tainted-Space/blob/master/classes/Creature.as

**Comment by EliteKiller693** [comment]
If the racial identifier isn't high enough then I can only assume my save is bugged then. Because it was still showing half gryvain even after spamming the gryvain transformatives to the point of being ineffective in-game. Not sure if that is a result of me having shitty luck or a possible side effect of the save editor?  Gonna go check in game again to make sure I'm not accidentally wasting your time. Thank you so much for taking a look at my issue though ^-^

**Comment by Wishbringer** [comment]
@EliteKiller693: The racial score is calculated ingame based on the actual bodyparts, nothing to do with the editor.
The save wouldn't affect this either, only way would be if there was a coding error calculating the gryvain score, in particular (quite sure that isn't the case).
Getting a score of 9+ one would need to have pretty much every body related gryvain affectation.
Check the links above to find out exactly what they are.
