### ISSUE TITLE
Missing edit options

### ISSUE THREAD

**Issue by Rhah-** [Chase-san/TiTsEd#2]
Not sure if issue, or just me being blind at 3am:

I see no option to adjust anal settings. I see the option in the xml doc, but nothing in the exe.
Am I just dumb or does the option only show if it's anything other than default?

Also:
The check boxes for 'cock virgin' and 'virgin' are kind of vague. Is there any way to add tooltip text when hovering over the checkboxes to give people a better idea of what the results of checking the box would be? I'm not even sure what the options do in game, apart from one of them obviously labeling your character as a virgin.
![2016-06-18_03-24-52](https://cloud.githubusercontent.com/assets/7822496/16169665/76e132a4-3504-11e6-88ed-692a1abb63b7.png)

**Comment by Chase-san** [comment]
I added some anal options in a past update, and more recently got merged in.

As for I Cock Virgin, I believe that means that as far as cocks go, your character is a virgin, where as the virgin flag on the cock itself defines that cock as a virgin (i.e. never used to penetrate). But any verification that anyone can give would be useful.
