### ISSUE TITLE
Perks page should not be accessible when a non PC character is selected.

### ISSUE THREAD

**Issue by Chase-san** [Chase-san/TiTsEd#23]
Currently if you edit a non-PC character, you can select the Perks page, which are PC only. The page should be disabled similar to how the items page is disabled for non-PC characters (I found this to be the easier solution).

Also we might want to consider a way to show that these pages are disabled on the bar. Either by removing them from the bar, or greying them out in some fashion.

**Comment by algoRhythm99** [comment]
This will be fixed in the next release.

**Comment by Chase-san** [comment]
Also, sorry for being inactive recently, went from super busy work to my vacation. Hopefully things will settle down now and I can get more work done on this as well.
