### ISSUE TITLE
Some items are not able to be differentiated easily.

### ISSUE THREAD

**Issue by Chase-san** [Chase-san/TiTsEd#25]
The Corny T Shirts are all the same now. I had this problem before with other items by using just the name, so I switched to formatting the end of the item id instead. However now that we have items that cause issues with either method.

We either have to have to create an algorithm that determines the best one to use or we add display names to each item.

Unfortunately, if we take the first option, we may have to fix it again in the future if it another curve ball comes. Where as the other option is very time consuming.

I have been meaning to revamp the items in the xml for a little while now, but not sure if I can put the time into it immediately.

**Comment by Chase-san** [comment]
The easiest solution I can think of right now, is adding a tip attribute to the xml and displaying that as the items tool tip. Which is sort of how CoCEd works if I recall.

**Comment by algoRhythm99** [comment]
I'm testing a fix for this locally, I added the variant value to the Corny T-Shirt items, as well as a tooltip for them.
The selection checks the variant value if it exists against the value in the xml.

**Comment by algoRhythm99** [comment]
Fixed in the next release

**Comment by Chase-san** [comment]
I am liking the look of the fix. I had some local stuff on restructuring the way the items work in the xml, but it is somewhat moot (as it is a data file no one should be editing anyway).

Also, first time I have seen the ?? operator used in C#. It was confusing to an old Java/C hand such as myself before I looked it up.

**Comment by Chase-san** [comment]
Closing as most of this issue is a subset of issue #28, and the parts that are not are fixed.
