### ISSUE TITLE
Items that require hasRandomProperties are not supported.

### ISSUE THREAD

**Issue by Chase-san** [Chase-san/TiTsEd#28]
After using minerva to look at the Corny T-Shirt they are not as simple as I would hope. I am removing them from the list of items for the moment because they require support for [hasRandomProperties](https://github.com/OXOIndustries/Trials-in-Tainted-Space/blob/a283d640a3411307da478873f72675b95a220074/classes/DataManager/Serialization/ItemSaveable.as#L75). This basically saves all the values for a given item, which means we would require a complete copy of the data for an item to add it properly.

Without this we will get the most generic version of a given item. That means writing the "variant" property to the save for the item means nothing without that flag as well. But if we have that flag we may need all of the items data. For now I think we might want to consider a way to add custom fields to any given item without them being a property in case we have a lot of them.

This will likely involve subtags of the sort `<Item ...><ItemField ID="hasRandomProperties" type="bool" value="true" /><ItemField ID="varient" type="int" value="1" /> </Item>`

I think that hard light variants also use this property.

**Comment by algoRhythm99** [comment]
Ick, I was afraid something like that might be necessary, but was hoping based on the item code the variant flag was enough.

**Comment by Chase-san** [comment]
Afraid not. Also TiTsEd might erase these flags when items are edited period. Meaning it may have been mutilating item data all along.

**Comment by Chase-san** [comment]
Actually it might be for those. But also requiring the hasRandomProperties flag. I have not personally tested it yet. Maybe we just need those two. But there are also hard light items and other things that may need different variables. So I will see about looking deeper into the item handling this weekend.

**Comment by Chase-san** [comment]
It is starting to look better in my item branch, but still needs a bit of work. Additionally I made it so we can add or remove item categories via the xml.

Soon as it is done you will be able to select any item variant we have defined in the xml.
