### ISSUE TITLE
Constructive Ideas

### ISSUE THREAD

**Issue by Epyxoid** [Chase-san/TiTsEd#32]
Firstly I would like to thank you for all the work You put it in this application, what is already handy and well-functioning. During that time I was using it I make a list what could make it even better like (small) new features and a few suggestions for the look. I write them down as short and clearly as possible:

- ~~max energy 133 if has perk "Heroic Reserves"~~
- ~~add "Current Shield" to General/Stats~~
- ~~make shield max to automatically change if the conditions change (equipped shield, perks)~~
- ~~show percentage next to core stats at General/Stats (actual/max)~~
- ~~add "Elasticity" to Body/General~~
- ~~add "lips descriptive word" (plump, fat, whorish, ect) to Lip Mod at Head/Face~~
- auto change body part flags to the new selected type's default flags when change type
----------------------------------------------------------------------
- add space between body part groups in Body/Generals (body ratings (plus elasticity), arm, leg, wing)
- ~~add main titles in Genitals, "Male Organs"to the left, "Female Organs" to the right~~
- ~~remove column title "Base", "Modifier" at Genitals(/Male Organs)~~
- change sequence to be consistent like:
   - body parts: (skin, hair, ear, antennae, horn, face, eye, tongue, lip, beard, arm, leg, wing, tail, tail genitalia, nipple, breast, ball, cock, vagina)
     1. type(race)/type(genital)
     2. color/tone/accent
     3. count/per breast
     4. lenght/width/size/rating
     5. flags
     6. style
     7. other
  - orifices in Body/Butt and Genitals/Vagina:
     1. wetness (anal, vaginal)
     2. looseness (anal, vaginal)
     3. bonus capacity (anal, vaginal)
     4. virginty (anal, vaginal)
- reorganize breast properties:
  - Breasts --> Chest
    * common nipple properties
  - Breasts
    * actual "breast row" properties (one always selected like at Cocks or Vaginas)
  - Lactation
    * milk production properties
    * good to know: you can lactate only if production training higher than 50% or you have "Mega Milk" or "Milk Fountain" perks
  - the "Butt" category may handier if moved to below "Vaginas" and rename tab to "Genitals and Anus" or something like that (after all it's a VaginaClass object in the game)
- minor things:
  - ~~group key items~~
  - ~~add subgroups to perk groups (Level 2 Auto Perk, Level 2 Class Perks...)~~

I hope my ideas will be usable!

**Comment by Chase-san** [comment]
I will need to break this down a bit to really tackle it. These should all be separated into a separate issue. 

Here are some examples of topics for the first set.
- [x] Update maximum shield based on equipped shield.
- [x] Add shield bonus for "Heroic Reserves" Perk.
- [x] Allow editing current shield amount.
- [x] Allow editing elasticity (suggested to be put in Body/General)
- [x] Add flair description for lip modifier.
- [x] Automatically update body part flags to defaults for given entry.

Minor issues can be grouped, but your bullet points would be a good starting place for separating those. I can do this when I have more time, or you can do it yourself.

**Comment by algoRhythm99** [comment]
Good ideas!

"max energy 133 if has perk "Heroic Reserves""

Oh, I had already added this, will be in the next release ^^

**Comment by algoRhythm99** [comment]
I added elasticity and genital spot editing to the Body/General section.
I also added:
* main titles in Genitals, "Male Organs" to the left, "Female Organs" to the right
* show percentage next to core stats at General/Stats"

**Comment by algoRhythm99** [comment]
I also simplified the XML, I refactored all the "type/color" stuff into single lists where appropriate.

**Comment by algoRhythm99** [comment]
Added groups for key items, also split perks into more specific groups.

**Comment by algoRhythm99** [comment]
Added shield support, see #43

**Comment by algoRhythm99** [comment]
Added lip flair tip

**Comment by meteor07** [comment]
sorry if this isn't a good time, but why isn't there a barbed cock flag?

**Comment by Stadlen** [comment]
Barbed cock is the feline cock type

**Comment by algoRhythm99** [comment]
Default flags is in v0.26

**Comment by algoRhythm99** [comment]
Marking this as closed
