### ISSUE TITLE
Merged Race and Fluids

### ISSUE THREAD

**Issue by Chase-san** [Chase-san/TiTsEd#35]
I am somewhat split on this. As much as I like having more options and simplifying the overall design of everything. I think merging these might confuse a number of users, not knowing which entries will be visible in game and which won't.

**Comment by algoRhythm99** [comment]
Yeah, I really wanted to have it both ways, but XML just isn't conducive to that.

My other thought was to create entities.. but that would be pretty ugly.

**Comment by Chase-san** [comment]
We might be able to just have an ID list for each of the selections, that way we only need to define the text once. Something like...

`<RaceTypeRefs>`
`    <RaceTypeRef ID="Antennae">0,6,16,43,60,64</RaceTypeRef>`
`    <RaceTypeRef ID="Face">0,1,2,3,4,5,6,9,11,12,14,17,18,19,29,24,25,26,27,39,40,45</RaceTypeRef>`
`</RaceTypeRefs>`

Actually writing that out it isn't significantly easier either.

**Comment by algoRhythm99** [comment]
We could combine that with disabling selection of items that are not valid for the given part, that way unless the ID was truly unknown, it would get a string name, but you couldn't select it.

Although I still don't like how my simplification had to mix Human and "None".. I really wish the game had separate values for those conditions, but that ship has sailed...

**Comment by Chase-san** [comment]
That is certainly an option.

**Comment by Chase-san** [comment]
I am going to say I don't want to release a new version until we have this sorted out. The old method may not have been ideal, but the change should probably be moved over to a branch until we can come up with a good solution.

**Comment by Chase-san** [comment]
I moved the list mergers over to the [List-Merge](/Chase-san/TiTsEd/tree/List-Merge) branch.
