### ISSUE TITLE
Cant edit saves?

### ISSUE THREAD

**Issue by awsomeo** [Chase-san/TiTsEd#37]
All it does is give me this error

[TiTsEd: 0.16.0.37627]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.Model.AmfReader.ReadPlainDataFile(AmfFile file, String& name)
   at TiTsEd.Model.AmfFile..ctor(String path)

**Comment by awsomeo** [comment]
Sorry if im being stupid X(

**Comment by Chase-san** [comment]
Are you trying to open a TiTs File?

**Comment by awsomeo** [comment]
Yes i am

**Comment by Chase-san** [comment]
TiTsEd does not support TiTs files, please see the [How To Use](https://forum.fenoxo.com/threads/titsed-a-save-editor.2809/#post-57478) section of the forum post for details on how to use TiTsEd.
