### ISSUE TITLE
Possible 'Fixed CumQ' description

### ISSUE THREAD

**Issue by tyran285** [Chase-san/TiTsEd#38]
After checking the game code, and afterwards testing in-game, i can confirm that this perk fixes the **cum quantity** to whatever is in value 1, so you won't ever cum less or more than that. (for male organs only)

thus we can take something akin to the amazonian virility perk description and go with
"Ensures you never ejaculate neither more nor less than value 1 of this perk"

**Comment by algoRhythm99** [comment]
Will be in next release.
