### ISSUE TITLE
Anno genitals

### ISSUE THREAD

**Issue by Stadlen** [Chase-san/TiTsEd#39]
when you load Anno it shows that she has 2 balls and vagina type "[ID#:56] Unknown" when she clearly does not in game

**Comment by algoRhythm99** [comment]
That is what the game defines her to have.
My copy of the TiTS source (from before it went private atleast), has an Anno.as file with:
`this.balls = 2;`
and
`vaginas[0].type = GLOBAL.TYPE_INHUMAN;`

`public static const TYPE_INHUMAN:int 								= 56;`

Many of the NPCs actually have fixed appearances, that aren't affected by the character info in the save.
