### ISSUE TITLE
i was copying lactaiad

### ISSUE THREAD

**Issue by thenonamezz** [Chase-san/TiTsEd#4]
[TiTsEd: 0.9.1.34918, TiTs Data: 28]
System.Reflection.TargetInvocationException: Destinationen for en aktivering udløste en undtagelse. ---> System.InvalidOperationException: StartAt kan ikke kaldes, mens der genereres indhold.
   ved System.Windows.Controls.ItemContainerGenerator.System.Windows.Controls.Primitives.IItemContainerGenerator.StartAt(GeneratorPosition position, GeneratorDirection direction, Boolean allowStartAtRealizedItem)
   ved System.Windows.Controls.Panel.GenerateChildren()
   ved System.Windows.Controls.Panel.OnItemsChangedInternal(Object sender, ItemsChangedEventArgs args)
   ved System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   ved System.Windows.Controls.ItemContainerGenerator.OnRefresh()
   ved System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   ved System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   ved System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   ved System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   ved System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   ved System.Windows.Controls.ItemCollection.SetCollectionView(CollectionView view)
   ved System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   ved System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   ved System.Windows.Data.BindingExpressionBase.Disconnect()
   ved System.Windows.Data.BindingExpression.Activate(Object item)
   ved System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
   ved System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   ved System.Windows.Controls.ItemContainerGenerator.UnlinkContainerFromItem(DependencyObject container, Object item, IGeneratorHost host)
   ved System.Windows.Controls.ItemContainerGenerator.RemoveAllInternal(Boolean saveRecycleQueue)
   ved System.Windows.Controls.ItemContainerGenerator.OnRefresh()
   ved System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   ved System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   ved System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   ved System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   ved System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   ved System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   ved System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   ved System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   ved System.Windows.Data.ListCollectionView.RefreshOverride()
   ved System.Windows.Data.CollectionView.RefreshInternal()
   ved System.Windows.Data.CollectionView.EndDefer()
   ved System.Windows.Data.CollectionView.DeferHelper.Dispose()
   ved System.Windows.Controls.ItemCollection.SetCollectionView(CollectionView view)
   ved System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   ved System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   ved System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   ved MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   ved MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   ved MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   ved System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   ved System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   ved System.Windows.Controls.TreeView.SetSelectedItem(Object data)
   ved System.Windows.Controls.TreeView.ChangeSelection(Object data, TreeViewItem container, Boolean selected)
   ved System.Windows.Controls.TreeViewItem.Select(Boolean selected)
   --- Slut på staksporing af indre undtagelser ---
   ved System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   ved System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   ved System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   ved TiTsEd.View.ItemsPage.rightTree_SelectedItemChanged(Object sender, RoutedPropertyChangedEventArgs`1 e)
   ved System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ved System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ved System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ved System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ved System.Windows.Controls.TreeView.ChangeSelection(Object data, TreeViewItem container, Boolean selected)
   ved System.Windows.Controls.TreeViewItem.Select(Boolean selected)
   ved System.Windows.Controls.TreeViewItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   ved System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   ved System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   ved System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   ved System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   ved System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   ved System.Windows.Controls.ItemsControl.ApplyItemContainerStyle(DependencyObject container, Object item)
   ved System.Windows.Controls.ItemsControl.MS.Internal.Controls.IGeneratorHost.PrepareItemContainer(DependencyObject container, Object item)
   ved System.Windows.Controls.Panel.GenerateChildren()
   ved System.Windows.Controls.Panel.EnsureGenerator()
   ved System.Windows.Controls.Panel.get_InternalChildren()
   ved TiTsEd.Common.ItemPanel.MeasureOverride(Size availableSize)
   ved System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   ved System.Windows.UIElement.Measure(Size availableSize)
   ved MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   ved System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   ved System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   ved System.Windows.UIElement.Measure(Size availableSize)
   ved System.Windows.Controls.StackPanel.StackMeasureHelper(IStackMeasure measureElement, IStackMeasureScrollData scrollData, Size constraint)
   ved System.Windows.Controls.StackPanel.MeasureOverride(Size constraint)
   ved System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   ved System.Windows.UIElement.Measure(Size availableSize)
   ved System.Windows.Controls.Control.MeasureOverride(Size constraint)
   ved System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   ved System.Windows.UIElement.Measure(Size availableSize)
   ved System.Windows.Controls.StackPanel.StackMeasureHelper(IStackMeasure measureElement, IStackMeasureScrollData scrollData, Size constraint)
   ved System.Windows.Controls.StackPanel.MeasureOverride(Size constraint)
   ved System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   ved System.Windows.UIElement.Measure(Size availableSize)
   ved System.Windows.ContextLayoutManager.UpdateLayout()
   ved System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   ved System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   ved System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   ved System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Chase-san** [comment]
This was caused by the use of a null value. I fixed it a few versions ago. But next time please use a gist for the stack trace and explain the error in the post.
