### ISSUE TITLE
Throw a understandable error when someone tries to load a .TiTs file.

### ISSUE THREAD

**Issue by Chase-san** [Chase-san/TiTsEd#40]
Since this comes up a lot, the program should throw a reasonable message when this is attempted. That way we get less bug reports about the same issue. This should have been the real bug that needed fixing from the start, short of adding support for .TiTs files.

**Comment by algoRhythm99** [comment]
I added a file extension check, as well as a file content check.
I have tested the file content check with the "Save to File"s that my own machine makes, but haven't yet had the time to verify for others.
It blocks .tits files masquerading as .sol files, but also blocks .sol files renamed to .tits files (not sure why someone would do that though.)
