### ISSUE TITLE
Raw Save State viewing

### ISSUE THREAD

**Issue by algoRhythm99** [Chase-san/TiTsEd#42]
It would be useful to view the raw save state values, ala minerva.

**Comment by algoRhythm99** [comment]
Working on this in the rawStateView branch for now

**Comment by Chase-san** [comment]
This sounds painful to implement. Good luck.

**Comment by KevinBlue18** [comment]
Good luck! I can't wait to see this completed because it's hard using ".minerva" in browser when it somtimes freezes.

**Comment by algoRhythm99** [comment]
I have viewing working.
Although it currently requires a new dependency (JSON.Net) and it makes the editor take forever to load currently, so not releasing just yet.

**Comment by algoRhythm99** [comment]
Fixed the performance issues, just working on making it look a little prettier then will merge to master for the next release

**Comment by algoRhythm99** [comment]
Viewing released in v0.29.0
