### ISSUE TITLE
Issues/improvements

### ISSUE THREAD

**Issue by Trogdor-the-Burninator** [Chase-san/TiTsEd#44]
-~~It only seems to account for 10 inventory slots. Right now it needs to account for at least 15 (Hidden Loot, the Cargobot, and the Insulated coat), but ideally, it should be able to account for unlimited items, as some users will have used minerva and/or custom builds of the game to add more to their inventory.~~
-Would be better if it could detect any item in the save and automatically add it to the list of items, but at least it doesn't burst into flames when it detects an item it doesn't recognize :)
-~~There are additional hairstyles available from the goo balls dropped by Ganrael that aren't options in the editor.~~
-~~I don't see any means of changing your Vanae Markings color.~~

**Comment by algoRhythm99** [comment]
Vanae Markings uses the "skin accent" color, which is on the General page.

**Comment by algoRhythm99** [comment]
- [x] Take "Hidden Loot", Cargobot and Insulated Coat into account for inventory max
- [x] Support unknown items
- [x] There are additional hairstyles available from the goo balls dropped by Ganrael that aren't options in the editor.

**Comment by algoRhythm99** [comment]
These will all be in the next release.
