### ISSUE TITLE
How do I launch the editor?

### ISSUE THREAD

**Issue by konodioda123** [Chase-san/TiTsEd#45]
I'm feeling very stupid, how do I actually launch it?

**Comment by konodioda123** [comment]
Nevermind I downloaded the wrong thing.

**Comment by konodioda123** [comment]
And again I'm too stupid to figure this out. How do I load a Slot save?

**Comment by Chase-san** [comment]
See how to use section here: https://forum.fenoxo.com/threads/titsed-a-save-editor.2809/

**Comment by konodioda123** [comment]
I'm good until point 6. My editor has none of the things it says on the post, only "Import".

**Comment by Chase-san** [comment]
- If you do not see any of these menus, ensure you are using a supported browser. If you are, try playing in a different supported browser.

**Comment by konodioda123** [comment]
I am plying of firefox. I tested it on Chrome and it doesn't seem to work either.

**Comment by Chase-san** [comment]
Which version of Windows are you using? You may also use the [Adobe Flash Standalone](https://fpdownload.macromedia.com/pub/flashplayer/updaters/24/flashplayer_24_sa.exe) player with a local copy.

**Comment by konodioda123** [comment]
I'm on windows 7.

**Comment by konodioda123** [comment]
Seems like using the adoble flash standalone thing worked. Thanks.
