### ISSUE TITLE
Savefile detected does not match the current game version

### ISSUE THREAD

**Issue by alfredapri** [Chase-san/TiTsEd#46]
Title says it all. I'm currently with the newest public build of the game (0.7.10), and the v0.18 save editor build. Any idea what happened?

**Comment by alfredapri** [comment]
For details: I updated the game a few days ago, as well as this save editor, and the save editor keeps loading the savefile from the previous game build, and not the current updated one.

**Comment by algoRhythm99** [comment]
Did the savefile come from an Android version?
Can you attach the savefile?
I use the editor with the latest backer version and it works just fine.

**Comment by alfredapri** [comment]
no, it's the pc version. any ideas?

**Comment by algoRhythm99** [comment]
Can you link the save file?

**Comment by alfredapri** [comment]
which one?
the old version or the new version from the editor?

**Comment by algoRhythm99** [comment]
The savefile that the editor cannot load.

**Comment by ffiveO** [comment]
[Faedir - 1791 days.zip](https://github.com/Chase-san/TiTsEd/files/738724/Faedir.-.1791.days.zip)
There.

**Comment by alfredapri** [comment]
[brokenthing.zip](https://github.com/Chase-san/TiTsEd/files/738732/brokenthing.zip)
There.

**Comment by algoRhythm99** [comment]
You won't be able to load (nor import) that file directly in the save editor.
But once I "re-saved" as a slot file (.sol) I was able to load it in the save editor ok.

**Comment by alfredapri** [comment]
But I can't even open the file :(
It says .tits file is not currently supported. And I can't save the current loaded (in chrome) savefile as .sol file

**Comment by algoRhythm99** [comment]
Right, you have to save from the game to a save slot.
Are you saying you can't save to a slot?
That would be a bug in the game or a problem with the browser.
Have you tried the stand alone flash projector?

**Comment by alfredapri** [comment]
So I'm supposed to save the file to a slot file. Yes, it appears I can only save as .tits directly from the game. I'll try the flash projector first.

**Comment by alfredapri** [comment]
And it worked. Thanks!
