### ISSUE TITLE
Inventory Editor Breaking Save

### ISSUE THREAD

**Issue by xBetaDragonx** [Chase-san/TiTsEd#48]
When the "T.S.T.Armor Mk II" is added to your inventory via the editor, upon loading your game, your save will be broken, giving the error "Load error(s) detected: Error #1065 Error: Could not load game data"
Currently, this is the only item I've come across with this error.

**Comment by Mister-Gregar** [comment]
Its an item for debugging, not normal gameplay. The same will happen if you take the tachyon beam laser or take the Advanced Slut Ray without the right flags. Just don't use the item.

**Comment by xBetaDragonx** [comment]
Appreciate the feed back Mister-Gregar
