### ISSUE TITLE
Starting the program

### ISSUE THREAD

**Issue by ghost** [Chase-san/TiTsEd#49]
Complete noob here, I'm not seeing any .exe file or any file to execute the program......

Help, how do I start it?

**Comment by algoRhythm99** [comment]
So you downloaded the latest release?
https://github.com/Chase-san/TiTsEd/releases/download/v0.21.1/TiTsEd_v0.21.1.zip
Right-clicked on the zip, checked the Unblock box
Unzipped the files into a folder
And you don't see the TiTsEd.exe?
