### ISSUE TITLE
TiTsEd Crashes on start

### ISSUE THREAD

**Issue by BadRaga** [Chase-san/TiTsEd#50]
I'm fairly sure this is due to me updating Windows 10 with the Windows 10 Creators update as TiTsEd worked with no issues before then no matter which version of TiTsEd I used. 
Now it crashes right at start, checking event viewer I get:

> Faulting application name: TiTsEd.exe, version: 0.16.0.0, time stamp: 0x58291946
> Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
> Exception code: 0xc000041d
> Fault offset: 0x000000000000fd0c
> Faulting process id: 0x1964
> Faulting application start time: 0x01d2b7bd246392fa
> Faulting application path: G:\Downloads\TiTsEd_v0.16\TiTsEd.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
> Report Id: e378ce6d-5aac-4c96-abfe-9f66069d41ff
> Faulting package full name: 
> Faulting package-relative application ID: 

AND
> Fault bucket , type 0
> Event Name: APPCRASH
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: TiTsEd.exe
> P2: 0.16.0.0
> P3: 58291946
> P4: d3d9.dll
> P5: 10.0.15063.0
> P6: 631de416
> P7: c000041d
> P8: 000000000000fd0c
> P9: 
> P10: 
> 
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A81.tmp.dmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B0E.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B1F.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B30.tmp.txt
> 
> These files may be available here:
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TiTsEd.exe_a9ae01268598b1856468f6dd31f39397e9d1d1b_00f283d2_26d592be
> 
> Analysis symbol: 
> Rechecking for solution: 0
> Report Id: e378ce6d-5aac-4c96-abfe-9f66069d41ff
> Report Status: 97
> Hashed bucket: 

I have AV, ESET installed but I also had that previously and it gave no issues, but to check I disabled it and still have the crash at start.

**Comment by algoRhythm99** [comment]
"0.16.0.0"
That is an old version, please try with the latest version.
https://github.com/Chase-san/TiTsEd/releases/tag/v0.22.2

**Comment by algoRhythm99** [comment]
"Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416" we're not doing anything with DirectX directly, so this would point to an issue with the XAML in .NET trying to drive the UI using hardware acceleration.

**Comment by BadRaga** [comment]
Okay I fixed the issue.
Its Part of the Windows 10 Creator update and RiviaTunerStatistics (Part of MSI Afterburner) If RTSS is closed TiTsEd works fine it RTSS is running it has to be set to Application Detection Level NONE. Apparently The Creators update has broken RTSS for multiple applications, so until RTSS is updated this can happen.
