### ISSUE TITLE
Problems Loading After Edit

### ISSUE THREAD

**Issue by MavenofMayhem** [Chase-san/TiTsEd#51]
I can find and edit my saves fine, but when i try to reload them into my game, they are not there. I am using the free TiTS build and playing in Chrome. I used the TiTSED program to load from and save to my directories, but its as if the game is no longer reading them.

**Comment by Stadlen** [comment]
maybe you are re saving them to  the wrong place?  Have you played on more than one browser? is so might have saved to the wrong browser.

**Comment by MavenofMayhem** [comment]
No, I only play on chrome. If i follow the directions on the smutosaur wiki i find one directory, but if i use the program and open up the directory it uses i get another. TiTS doesnt seem to read the files in either directory.

**Comment by algoRhythm99** [comment]
"but when i try to reload them into my game, they are not there"
Not sure by what you mean here, are you saying that the game can't find your updated saves?
The filename has to be TiTs_N.sol, where N is some number between 1 and 14.

**Comment by MavenofMayhem** [comment]
Yeah, thats what they are saved as. When i go to the ingame load screen, the files simply arent in the list, all the slots say "EMPTY."

**Comment by algoRhythm99** [comment]
So you can save and load normally, without using the editor at all?
But when you use the editor the game can't find the saves any longer?

**Comment by MavenofMayhem** [comment]
Exactly. I just downloaded and tried firefox and didnt have this problem. Must have been a hiccup with chrome.
