### ISSUE TITLE
Pregnancy editing

### ISSUE THREAD

**Issue by algoRhythm99** [Chase-san/TiTsEd#53]
Just putting this here to keep track of the request

**Comment by algoRhythm99** [comment]
Experimental support added in 0.26.6

**Comment by moopdoop** [comment]
Not sure if this is where I should put it but currently editing pregnancies seem to make it so I can't fly or move.

Edit: At least it does for me.

**Comment by algoRhythm99** [comment]
Removing/adding/resetting wombs should be fixed 0.26.8.

**Comment by algoRhythm99** [comment]
Marking this complete, since only issues are with required status changes
