### ISSUE TITLE
Am I doing this right?

### ISSUE THREAD

**Issue by Mister-Gregar** [Chase-san/TiTsEd#54]
I think the editor has the max HP values for smuggler and mercenary backwards. Either that, or something is fuggy with my download. 

Also, I'm assuming that the SSTD immune perk be in the next version, yes? My question is, would there be a way for the program to add new perks and statuses on its own? It already does that on a temporary, per session basis, but I'm curious if it's possible for it to add the stuff to the list permanently?

Sorry if this has been answered/addressed already or if I'm using the issues section wrong. Here's a kitten.
![izdexh_1247](https://cloud.githubusercontent.com/assets/24524812/26469564/6e59c3aa-4168-11e7-955e-1ddf006d7c88.jpg)

**Comment by algoRhythm99** [comment]
Yep, it had Mercenary and Smuggler mixed up, that is fixed for next release.
It also wasn't taking status effects into account, also in next release.
It still doesn't take item fortification values into effect, though.

Any perks available in the public build will be available after the next public build, or that I have seen in an existing save.
If you want to post a save with the perk I can get it added ahead of the public build.

I'm not sure what you mean by "adding stuff to the list permanently"?
Do you mean taking new effects that the editor sees in saves and remembering it across sessions?
That is certainly a possibility, though nothing that will be worked on anytime soon.
You can always edit the TiTsEd.Data.xml file manually.

**Comment by Mister-Gregar** [comment]
> If you want to post a save with the perk I can get it added ahead of the public build.

Where can I post that? Apparently the site doesn't accept files that aren't PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. I'll try adding as a ZIP, but idk if that will bork anything. I am a scrub.

[TiTs_1.zip](https://github.com/Chase-san/TiTsEd/files/1033757/TiTs_1.zip)


> Do you mean taking new effects that the editor sees in saves and remembering it across sessions?

Yes, exactly this. Take your time, I'm pretty sure this game won't be done any time this decade. Fen's gonna milk it. And if he doesn't, it won't matter since it won't do anything if the game's complete.

> You can always edit the TiTsEd.Data.xml file manually.

I am a scrub who doesn't know how that would work.

**Comment by algoRhythm99** [comment]
v0.23.1 released with HPMax bug fix and STD Immune perk
