### ISSUE TITLE
Some unaccessible features (mainly about mimbranes)

### ISSUE THREAD

**Issue by KWJG** [Chase-san/TiTsEd#57]
Mimbranes. Only accessible if you already have mimbrane, in the "unknown raw data".

Minimum looseness, minimum wetness of orifices.

Breast rating bonus given by mimbrane. It should be accessible just like the one on the ass.

**Comment by algoRhythm99** [comment]
Can you link a save file?

The "wetness" is itself the "minimum wetness".

So you want to be able to modify the minimum looseness along with the looseness itself?

**Comment by Mister-Gregar** [comment]
I heard you need a save with mimbranes? I got one, it has all mims, but...
Well, hope you can afford chemotherapy. The character is cancer.
[TiTs_3.zip](https://github.com/Chase-san/TiTsEd/files/1167717/TiTs_3.zip)


I am sorry.

**Comment by Mister-Gregar** [comment]
Not sure if double posting is okay or not, but had to ask: does the save file work? Apparently a save from a backer file doesn't work on a public game (makes sense) but I didn't consider that people would be using public builds. Do you need the stuff on a public version save?

**Comment by algoRhythm99** [comment]
I am a backer, haven't had a chance to look at it yet, and won't till the weekend at the earliest.

**Comment by Mister-Gregar** [comment]
Just wanna give this a slight bump for the mimbranes. Also, the flags for skin has a missing option: aphrodisiac. Value is 11, it's used by the frog TF.

Question, is it possible for the editor to permit changing the tooltips of status effects? Hair Flower and Arm Flower use those to dictate color.

**Comment by algoRhythm99** [comment]
Mimbrane support will be in the next release.

**Comment by algoRhythm99** [comment]
Changing tooltips won't be possible for awhile yet. Would require refactoring how they work quite a bit, since the description is used to match the "XML" version with the save version.

**Comment by algoRhythm99** [comment]
Mimbrane support released
