### ISSUE TITLE
Unable to launch editor

### ISSUE THREAD

**Issue by ZedBee22** [Chase-san/TiTsEd#59]
when opening the editor file a fetal error opens saying that the XML.Data file could not be opened due to it already being in use or not having permission to read it from where it is located.
the file is not open and i have placed the file in different location but nothing changes.

**Comment by algoRhythm99** [comment]
1. Right-click on the zip file
2. Check the 'Unblock' and click Apply
3. Unzip the files into a directory
4. Run the TiTsEd.exe
