### ISSUE TITLE
Won't open, at all.

### ISSUE THREAD

**Issue by DaRealLaael** [Chase-san/TiTsEd#60]
I sent TiTsEd and all of it's required contents to Downloads, but when I try to open it, it simply opens as a tab on the window bar. When I click said tab, it will not open although (since im on windows 10 although im sure this exists as a feature for other OSes) when i hover over it, the window is there like it's still loading but the window preview is invisible. I've tried extracting to other folders, even giving it it's own folder, but nothing's working. Help?

**Comment by algoRhythm99** [comment]
1. Right-click on the zip file
2. Check the 'Unblock' and click Apply
3. Unzip the files into a directory
4. Run the TiTsEd.exe
