### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by KasakirX** [Chase-san/TiTsEd#62]
Hey, downloaded and extracted the latest release, but can't use it. 
There seems to be nothing to open in any of the folders?

**Comment by KasakirX** [comment]
I'm on windows 10 pro btw

**Comment by algoRhythm99** [comment]
If you have folders, that means you downloaded the source, not the binaries.

Download the binaries:
https://github.com/Chase-san/TiTsEd/releases/download/v0.24.4/TiTsEd_v0.24.4.zip

Right-click on the zip, and select Properties
Check the 'Unblock', click apply
Unzip to somewhere and run TiTsEd.exe
