### ISSUE TITLE
Error #1069

### ISSUE THREAD

**Issue by Mister-Gregar** [Chase-san/TiTsEd#63]
Starting in version  24.2, and continuing in the following versions including 24.5, adding a new vagina to a character causes saves not to load in game. The game gives Error #1069.  Removing the vagina frees up the save. Editing a pre-existing vagina is fine.

I think the issue is that the bugged vaginas have the "fullness" integer present. Removing that integer via  minerva allows the saves to load again.
Attached should be a bugged and unbugged version of a save (slot 2) made with 24.5. The unbugged version was edited by minerva only to remove the "fullness" entry.
[TiTs Saves.zip](https://github.com/Chase-san/TiTsEd/files/1206502/TiTs.Saves.zip)

**Comment by algoRhythm99** [comment]
This should be fixed in 25.0

**Comment by Mister-Gregar** [comment]
Can confirm. Very fixed.

Edit, I know nothing about who's allowed to close issues, I see an option, but I don't wanna do something I aint allowed to.
