### ISSUE TITLE
.sol cannot into TiTs :'(

### ISSUE THREAD

**Issue by JohnSmithPony** [Chase-san/TiTsEd#64]
Basically, .sol files are DEFINITELY in the folder, but when I go in game, and click load file, only .TiTs files appear in that folder. Not the edited .sol files I just made.
...
That's it. What now?

By the way, I've tried this on Firefox, Microsoft Edge, Chrome, an Android .apk, and a .sfw projector, all on TiTS 0.7.78, with TiTsEd 0.25. OS is Windows 10. Also, I have tried naming the .sol files to (As algoRhythm99 put it,) "TiTs_N.sol, where N is some number between 1 and 14."

Ps. Apologies, if this is too much like an existing topic. I hope I explained my issue clearly enough.
Pss. I don't even know if I'm doing this the right way. I had to guess this far. Some instructions would be very helpful for newbies like myself.

**Comment by Mister-Gregar** [comment]
The "Load File" function in TiTS (the game) is meant solely for the .tits saves. The .sol files are meant to be used with the normal "Save" and "Load" function, and only will work when in the proper directory.  The Export function of the TiTEd program can be used to save your file as a .tits file that you can use with the "Load File" function in game, and can be saved to whatever location you want.

As for .sol files: Try heading to " %AppData%\Macromedia\Flash Player\#SharedObjects\ " (copy paste as file path in windows explorer, do not include quotation ["'] marks) and looking for a folder with random letters and numbers. In that folder, another folder named localhost should be where you place .sol files for the game's normal Save/Load functions to detect them while using the Standalone Flash Player. The save editor will save files in that directory normally by going to "Save As>Local (Standard)" and selecting a slot for the save. Manually placing a save there may not have it be read in the proper slot (or at all) by the game.

**Comment by JohnSmithPony** [comment]
Ok... making progress. Thanks for that quick response too!

So...
TiTsEd can save as a .tits file? How? If I just type .tits at the end, it says "Got file, verifying...Data property version was expected, but unset. This save is possibly corrupt!" I don't know any other way of making it a .tits file.

By the way, just as a test, I just downloaded Corruption of Champions, and its respective editor, and that worked perfectly. So... yeah. I think all I need now, is a way to make a non-corrupted .tits file, and I'll be set. That will probably be my last big issue.

**Comment by SoleZest** [comment]
I don't think your supposed to edit the .tit files here's how I edited my saves
1.) save your game to a slot(not a file)
2.) click on the Open button, then the LocalWithNet button your your save slots will be there
3.) edit what you want to edit(editing items may or may not cause an error when loading)
4.) click on the Save As button, then the LocalWithNet button to choose which slot to save to

**Comment by JohnSmithPony** [comment]
Ah! Ok, it works!
Surprisingly, it works a little differently to Corruption of Champions, but at least it works now!

Thank you! 
(I'm just one of those people who has something going wrong with about half the games I play, be it a confusing installation/ method, corrupt file, notorious Norton (the antivirus), weird glitches from alpha/ beta games, noob-like user error, etc... So thanks for bearing with me.)

**Comment by Mister-Gregar** [comment]
Ok, so, I didn't see the earlier replies in this chain or I would have responded sooner.

> How? If I just type .tits at the end, it says "Got file, verifying...Data property version was expected, but unset. This save is possibly corrupt!

You changed the file extension manually. Never do this. The file-type .tits is made by the game's save to file function. .tits and .sol files are completely different, and changing the file extension will not swap the two. Instead you wind up corrupting it, as you did. The save editor can read .tits files made from the game by using the Import function and looking for .tits files. The save editor reads the .sol files by using the normal save to slot function that SoleZest described above.

There's no real reason to edit .tits files anyway unless you archive a lot of characters like I do or need to edit saves for your android device.  It sounds like you're on PC, so you probably don't need .tits files.

I'm glad to hear that everything is working for you now.
