### ISSUE TITLE
Updating flag checkboxes

### ISSUE THREAD

**Issue by DernaSteele** [Chase-san/TiTsEd#68]
I'm currently working on a feature where the default flags for a cock type are set when changing between the different types. The only issue I am having is getting the GUI to recognise the change and update the checkbox's GUI element accordingly.

The checked status is being updated by accessing the `CockVM.CockFlags` property, and changing the status of `FlagItem.ItemChecked` to be true if it is a default flag, otherwise false. I have confirmed that this is functioning correctly as saving the file and re-opening it shows the flags correctly set.

Could someone please advise as to how to get the checkboxes on the GUI to update with the change, I can't seem to find any such methods in any of the classes.

**Comment by algoRhythm99** [comment]
This should work:
`GameVM.OnPropertyChanged(null);`

**Comment by DernaSteele** [comment]
No luck with any of the `OnPropertyChanged()` or `NotifyPropertyChanged()` methods for any class. Tried it with a variety of different values, including null. Always results in no change to the UI.

**Comment by algoRhythm99** [comment]
Can you attach a pull request or a branch?
Might be able to tell what is wrong then.

**Comment by DernaSteele** [comment]
You can view my current changes at DernaSteele@a2b46b59b137ac3a2af5fd4a99afc8e7d6002c3f

I've verified that the flags are actually changing properly, as this can be seen if you swap to another item in the array and then back, or if you save and reload the file.

**Comment by algoRhythm99** [comment]
I fixed this issue here..
d333a072746ca68913be5321d461ed0e0d3f4629

**Comment by DernaSteele** [comment]
Thanks for the help!

**Comment by algoRhythm99** [comment]
Merged into master
