### ISSUE TITLE
No longer able to detect newer version saves. (.127/.128)

### ISSUE THREAD

**Issue by jaguarofthefluff** [Chase-san/TiTsEd#72]
Title pretty much says it. TiTsEd can no longer find/edit newer save files. :C It seemed to work in .127 for a bit, But in .128 it's completely stopped

**Comment by algoRhythm99** [comment]
Do you mean with the AIR version?
It is working just fine with the SWF version + standalone flash player, still.

**Comment by algoRhythm99** [comment]
Just added support for the AIR executable's save locations in 0.26.4
