### ISSUE TITLE
Pregnancy?

### ISSUE THREAD

**Issue by XanthosTheoric** [Chase-san/TiTsEd#75]
Welp, I made the mistake of playing with my womb count.  That broke everything.  Now I can play the game only when I set it to no wombs.  But when doing that if something knocks my character up, I get this error.

```
_Flash Player: Desktop - Windows 10
Flash Version: WIN 28,0,0,126
Game Version: 0.7.141

Error Name: TypeError
Error Mesg: Error #1009
TypeError: Error #1009
	at classes::Creature/isPregnant()
	at classes::TiTS/bothriocPidemmeLossSelector()
	at classes::TiTS/bothriocPidemmePCLoss()
	at Function/()
	at classes::TiTS/buttonClick()_

```
Likewise if I try to add a single womb I get another error,

```
_Flash Player: Desktop - Windows 10
Flash Version: WIN 28,0,0,126
Game Version: 0.7.141

Error Name: TypeError
Error Mesg: Error #1009
TypeError: Error #1009
	at classes::Creature/hasPregnancyOfType()
	at classes.DataManager::DataManager/executeGame()
	at classes.DataManager::DataManager/loadGameData()
	at classes::TiTS/buttonClick()_
```

So I don't know what to do to fix the problem, and I've been trying to debug it so long that I'm afraid I no longer have a back-up to my original file.

Please help!?

**Comment by algoRhythm99** [comment]
Gonna need a save file to look at.
Also, this is why the pregnancy editing is still experimental :p

**Comment by XanthosTheoric** [comment]
There you go.  If it's not too much to ask, could you possibly fix and repost the file for me if you can figure out what's wrong with it.

[TiTs_2.zip](https://github.com/Chase-san/TiTsEd/files/1755890/TiTs_2.zip)

**Comment by XanthosTheoric** [comment]
Also, yes, I will avoid using the pregnancy editing until it's not experimental.  lol  I just want my game back.  :(  Huge investment of time in that file.  xD  Stupid me.  I really ought to have made back-ups like recommended.

**Comment by algoRhythm99** [comment]
[TiTs_2.zip](https://github.com/Chase-san/TiTsEd/files/1756677/TiTs_2.zip)

This will be fixed in the next release of the editor.
