### ISSUE TITLE
open and save as file menus broken

### ISSUE THREAD

**Issue by pixelade** [Chase-san/TiTsEd#76]
Whenever I try to open or save a file, the pane to select a files always disappears before I manage to click on it. I have to move my cursor back and forth several times to actually click on it. # #

**Comment by algoRhythm99** [comment]
That sounds like you have faulty mouse drivers or a bad trackpad.

**Comment by pixelade** [comment]
I haven't seen it happen on any other program. Is there anything else it could be?

**Comment by algoRhythm99** [comment]
Some kind of program that captures the focus maybe, or a faulty keyboard also possibilities.

**Comment by InSimpleTermsJordan** [comment]
Could you try plugging in a different mouse and see if it changes anything?

**Comment by pixelade** [comment]
An update fixed it. I'm not sure which one. If it ever pops up again I'll open another issue.
