### ISSUE TITLE
Tab to view racial scores

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [Chase-san/TiTsEd#85]
A separate tab for viewing each of the PC's racial scores (and possibly what factors contribute to each of them) (unless there's already some way to view them easily ingame)

**Comment by algoRhythm99** [comment]
This would be extremely tedious to implement.
The game code for this functionality is *many*, *many* if statements.
Doable, but not something I would want to tackle any time soon.
Feel free to submit a pull request :)

**Comment by algoRhythm99** [comment]
Actually, it would probably just be best to request the numbers get shown in the codex in game.

**Comment by InSimpleTermsJordan** [comment]
[Went and made a pull request on the TiTS-Public repo to add a racial scores section to the codex stats page](https://github.com/OXOIndustries/TiTS-Public/pull/118)
