### ISSUE TITLE
How does modifiers work?

### ISSUE THREAD

**Issue by lchronosl** [Chase-san/TiTsEd#86]
I don't really understand how the modifiers work, specially the Combat and Core stats. Messing around with them apparently only affects max combat stats, but seems to make no difference on core stats, melee and ranged damage an the like. Could someone explain it?
And since we are talking about modifiers, do all of them work the same way (in Body>General and Genitals)?

**Comment by algoRhythm99** [comment]
Modifiers are taken into account in certain calculations, but not all.
Many status effects add modifiers (which can be both positive or negative).
You would have to look at the game source code to see which modifiers actually do anything.
