### ISSUE TITLE
A way to change values for items

### ISSUE THREAD

**Issue by Awesatron** [Chase-san/TiTsEd#87]
it would be nice to be able to go in and change the specific values for different items, such as the possibility of different transformatives dong specific changes and for people interested or just wanting to fuck around, you could add the ability to change weapon damage and the amount of armor a shield gives you.

**Comment by algoRhythm99** [comment]
Not possible. 
With the exception of a few rare items, the item stats are hardcoded in the game code.
The only thing saved in your saves is the item class name.
