### ISSUE TITLE
Unable to use editor. Failure to launch.

### ISSUE THREAD

**Issue by ChaosRemnant** [Chase-san/TiTsEd#88]
Even when I have unblocked the zip file. It still gives me this error.
![capture](https://user-images.githubusercontent.com/22418241/51002082-cff61780-14f7-11e9-8d90-e68b6c9dffbc.PNG)
It is in a different folder than my downloads. Ran it in administrator. Nothing helps.

**Comment by algoRhythm99** [comment]
Did you actually unzip the files?
