### ISSUE TITLE
Program crashes when loading save, but then works afterwards

### ISSUE THREAD

**Issue by someone181** [Chase-san/TiTsEd#93]
The first time I try to load a file (using the Open->Local (Standard) menu), the program crashes with this message:

> [TiTsEd: 0.29.5.41435, TiTs Data: 33]
> System.UnauthorizedAccessException: Access to the path '636882895065829365.bak' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileInfo.Delete()
>    at TiTsEd.Model.FileManager.CreateBackup(String sourcePath)
>    at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Symptoms:**
The thing that's weird is that if I start the application and try loading the same file again, it works fine. Once that happens, I can save and load that specific file as much as I want without issue (as long as I don't close the program). If however, I try to load a _new_ file, it will crash with the same error again, and the same results (the new file is now the stable file if I reopen the program).  

**Other info that may help:**

- This is not a new error; the first build that had the issue was TiTsEd_v0.27.9, and the previous build I used (which was stable for me) was TiTsEd_v0.26.2. Whatever the problem is was introduced somewhere between those two versions. (For the record, the other builds I've used were v0.29.0, v0.29.1, and v0.29.2, all of which give the exact same error message with the exact same results.)

- The problem is still present with a 100% clean file (i.e. I start the game, save at the end of the tutorial, try to load that fresh save with the program, and encounter the same bug).

- Since "maybeFullPath" is the name of one of the error variables, the only guess I have is that the file path is too long. Just in case (for testing purposes), the path for the program's base folder is "D:\All Grownups\Games\TiTS\TiTsEd_v0.29.5" and the path to the save files is "C:\Users\ryan_\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\5W5D27DU\localhost"

- I use the .swf version of the game

This isn't _critical_ to solve since I have an easy workaround, but at the same time it's annoying enough that I've created a GitHub account solely to report this issue. Let me know if you need any more info.

Thanks!

**Comment by algoRhythm99** [comment]
System.UnauthorizedAccessException: Access to the path '636882895065829365.bak' is denied.

This means the program is getting access denied when trying to create the backup file for the save.
Only thing I can think of is an anti-virus application interfering.

**Comment by algoRhythm99** [comment]
Can you try this version?
https://github.com/Chase-san/TiTsEd/releases/tag/v0.30.4

**Comment by someone181** [comment]
The new version _may_ have fixed it. I say "may have" because I couldn't actually get the normal program to extract (every file in the "TiTsEd_v0.30.4.zip" folder except for "CoCEd License.txt", "TiTsEd License.txt", and "TitsEd.Data.xml" threw an "Error 0x80004005: Unexpected error. An unexpected error is keeping you from copying the file." exception, and re-downloading the file and restarting my computer didn't help). However, I _was_ able to extract the source code. When I compiled and ran that (using Visual Studio Community 2019), the program ran and didn't throw any errors when I tried loading different saves. Hooray! 

So it _seems_ to be fixed, but I know from experience that sometimes (especially when dealing with external folders and files) new problems crop up when running the program from its published executable vs. debugging in the VS development environment. So if you could re-upload a copy of TiTsEd_v0.30.4.zip (or re-zip it and upload that, sometimes that helps too), we can be _sure_ that the error is fixed. (And if it isn't, we'll at least have narrowed it down to a problem that _doesn't occur_ when being run from the debug location). 

Thanks!

**Comment by algoRhythm99** [comment]
Updated the zip file

**Comment by someone181** [comment]
New file works with no error  messages! Thank you very much for your help!
