### ISSUE TITLE
The editor doesn't launch properly.

### ISSUE THREAD

**Issue by neesema** [Chase-san/TiTsEd#96]
The editor simply open up as a title bar and is impossible to use. I've repaired net framework to be sure, and ran the extractor as administrator but the problem persists. 
Version 0.27.11 and below work properly but all the more recent ones do not. Any reason you could isolate? 
Illustration of the problem : https://i.imgur.com/QmEe73o.png

**Comment by algoRhythm99** [comment]
The app itself isn't failing the launch there, its just not expanding the window.
Delete %LOCALAPPDATA% folder
It will still show up small, but you should be able to resize it.

**Comment by neesema** [comment]
That was it, thank you.
