### ISSUE TITLE
Not sure about an update

### ISSUE THREAD

**Issue by FearTheDee** [Chase-san/TiTsEd#97]
The "master" file or whatever keeps saying it's getting updated, but I can't use that it seems.
However the most current release of the application (0.30.3) keeps telling me there's an update and I just don't see it. I even links back  to it's own download from September.

**Comment by algoRhythm99** [comment]
The most current release was 0.30.4.
Not sure what you mean by "master" file?

**Comment by FearTheDee** [comment]
The main page with all the file names or whatever, when I click "Clone Download" it calls it a master file.
Where can I download 0.30.4 because I can't seem to see it. Just version 0.30.3, and the update for my version just brings me back to 0.30.3.

**Comment by FearTheDee** [comment]
Nevermind it suddenly started working for some reason after closing the old TiTS editor and restarting my browser. I can see the most up to date version now.

**Comment by FearTheDee** [comment]
Hmm, now that I've downloaded 0.30.4 its saying that there are some unexpected payloads after extracting. Gives me a thing saying "Header:" for both TitsEd.data.xml and TitsEd.exe and they aren't extractable, so it's non functioning.

**Comment by algoRhythm99** [comment]
I replaced the release zip. 
I think I know what you were referring to with "master" file. 
That link is a zip of the source code of the master branch, so it calls it master.zip. 
Unless you plan on compiling it yourself that isn't useful to you.
